version: 0.2
env:
  secrets-manager:
    NPM_TOKEN: arn:aws:secretsmanager:us-west-2:779521627844:secret:prod/npmjs/token-rEDLLX
phases:
  install:
    commands:
      - cd packages/cdn/
      - PACKAGE_VERSION=$(npm run display-version --silent)
      - echo Set PACKAGE_VERSION to $PACKAGE_VERSION
      - cd ../..
      - echo Setting NPM token
      - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - echo Installing...
      - npm install -g npm@10.5.0
      - npm ci

  build:
    commands:
      - echo Building...
      - npm run build

  post_build:
    commands:
      - echo Replacing current SDK in S3
      - aws s3 cp packages/cdn/dist/browser/appfit.js s3://appfit-prod-cdn-storage/browser-sdk/appfit.js
      - aws s3 cp packages/cdn/dist/legacy-browser/appfit-legacy.js s3://appfit-prod-cdn-storage/browser-sdk/appfit-legacy.js

      - echo Archiving build in S3
      - aws s3 cp packages/cdn/dist/browser/appfit.js s3://appfit-prod-cdn-storage/browser-sdk/appfit-v$PACKAGE_VERSION.js
      - aws s3 cp packages/cdn/dist/legacy-browser/appfit-legacy.js s3://appfit-prod-cdn-storage/browser-sdk/appfit-legacy-v$PACKAGE_VERSION.js

      - echo Publishing to NPM
      - npm run deploy:publish
