version: 0.2
env:
  secrets-manager:
    NPM_TOKEN: arn:aws:secretsmanager:us-west-2:205830496597:secret:dev/npmjs/token-oL0xXe
phases:
  install:
    commands:
      - cd packages/cdn/
      - PACKAGE_VERSION=$(npm run display-version --silent)
      - echo Set PACKAGE_VERSION to $PACKAGE_VERSION
      - cd ../..
      - echo Setting NPM token
      - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - echo Installing...
      - npm install -g npm@10.5.0
      - npm ci

  build:
    commands:
      - echo Building...
      - npm run build
      - echo Running tests...
      - npm run test

  post_build:
    commands:
      - echo Copying to S3
      - aws s3 cp packages/cdn/dist/browser/appfit.js s3://appfit-dev-cdn-storage/browser-sdk/appfit-v1-browser.js
      - aws s3 cp packages/cdn/dist/legacy-browser/appfit-legacy.js s3://appfit-dev-cdn-storage/browser-sdk/appfit-v1-legacy.js

      - aws s3 cp packages/cdn/dist/browser/appfit.js s3://appfit-dev-cdn-storage/browser-sdk/appfit-v$PACKAGE_VERSION.js
      - aws s3 cp packages/cdn/dist/legacy-browser/appfit-legacy.js s3://appfit-dev-cdn-storage/browser-sdk/appfit-legacy-v$PACKAGE_VERSION.js
